name: Metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: files
          committer_message: 'build: update `${filename}`'

          # Options
          user: matheusnunesismael
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
